POST https://rocketseat-nodefromscratch.onrender.com/videos
Content-Type: application/json

{
    "title": "Vídeo node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET https://rocketseat-nodefromscratch.onrender.com/videos

###
PUT https://rocketseat-nodefromscratch.onrender.com/videos/52f22b12-f03f-4690-a5d8-7e19e3148930
Content-Type: application/json

{
    "title": "Vídeo 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE https://rocketseat-nodefromscratch.onrender.com/videos/e9902b8b-774f-4fde-b289-e88c63676514


